import PedigreeGovedina100g from "./SlikeProizvoda/PedigreeGovedina100g.jpg";
import AcanaDog2kg from "./SlikeProizvoda/AcanaDog2kg.jpg";
import AcanaCat1_8kg from "./SlikeProizvoda/AcanaCat1,8kg.jpg";
import AkinuKonzervaGovedina from "./SlikeProizvoda/AkinuKonzervaGovedina.jpg";
import AkinuKonzervaPiletina from "./SlikeProizvoda/AkinuKonzervaPiletina.jpg";
import ZoluxPapagaj from "./SlikeProizvoda/ZoluxPapagaj.jpg";
import ZoluxAmZaMacku from "./SlikeProizvoda/ZoluxAmZaMacku.jpg";
import ZoluxOgrlica from "./SlikeProizvoda/ZoluxOgrlica.jpg";
import ZoluxOgrlicaSaDrzacem from "./SlikeProizvoda/ZoluxOgrlicaSaDrzacem.jpg";
import ZoluxPovodacZaMacke from "./SlikeProizvoda/ZoluxPovodacZaMacke.jpg";
import ZoluxKavezSaPostoljem from "./SlikeProizvoda/ZoluxKavezSaPostoljem.jpg";
import ZoluxKavez from "./SlikeProizvoda/ZoluxKavez.jpg";
import ZoluxPojilica from "./SlikeProizvoda/ZoluxPojilica.jpg";
import ZoluxStalakZaKavez from "./SlikeProizvoda/ZoluxStalakZaKavez.jpg";
import ZoluxNutrimealHranaZaCincile800g from "./SlikeProizvoda/ZoluxNutrimealHranaZaCincile800g.jpg";
import ZoluxEhopTriKavezZaHrčke from "./SlikeProizvoda/ZoluxEhopTriKavezZaHrčke.jpg";
import flamingoDinaLopticaZaPse from "./SlikeProizvoda/flamingoDinaLopticaZaPse.jpg";
import ZoluxKoska from "./SlikeProizvoda/ZoluxKoska.jpg";
import FlamingoIgračkaMišnaNavijanjeAsher from "./SlikeProizvoda/FlamingoIgračkaMišnaNavijanjeAsher.jpg";
import FlamingoIgračkaŠtapsaPerjem from "./SlikeProizvoda/FlamingoIgračkaŠtapsaPerjem.jpg";
import FlamingoIgračkaŠtapZaPecanje from "./SlikeProizvoda/FlamingoIgračkaŠtapZaPecanje.jpg";
import AcanaHeritageAdultSmallBreed6kg from "./SlikeProizvoda/AcanaHeritageAdultSmallBreed6kg.jpg";
import AcanaHeritagePuppyJunior2kg from "./SlikeProizvoda/AcanaHeritagePuppy&Junior2kg.jpg";
import AkinuMinistickiesKomadići from "./SlikeProizvoda/AkinuMinistickiesKomadići.jpg";
import AkinuCrunchiesTrioMixPoslasticezaMačke from "./SlikeProizvoda/AkinuCrunchiesTrioMixPoslasticezaMačke.jpg";
import VerseleLagaCompleteChinchillaDegu500g from "./SlikeProizvoda/Versele-LagaCompleteChinchillaDegu500g.jpg";
import VitakraftPelletsHranaZaČinčile1kg from "./SlikeProizvoda/VitakraftPelletsHranaZaČinčile1kg.jpg";
import KongIgračkaAirDogTegsaLopticama from "./SlikeProizvoda/KongIgračkaAirDogTegsaLopticama.jpg";
import WhiskasBriketiTunjevina300g from "./SlikeProizvoda/WhiskasBriketiTunjevina300g.jpg";


export const listaProizvoda = [
    {
        id: 1,
        vrsta: "Hrana",
        Slika1: PedigreeGovedina100g,
        naslov: "Pedigree Adult Govedina 100g",
        opis: "Pedigree je jedan najpoznatijih brendova hrane za pse. Brend pripada američkom gigantu MARS, a prodaja Pedigree hrane ima kontinuirano visok obim u Srbiji i svetu, budući da je cena povoljna a kontrola kvaliteta na dobrom nivou.",
        cena: 75,
        zivotinja: "Pas",
        kolicina: 1,
        popust: undefined,
      },
      {
        id: 2,
        vrsta: "Hrana",
        Slika1: AcanaDog2kg,
        naslov: "Acana Dog Classic 2kg",
        opis: "Acana hrana za pse proizvodi se u Kanadi, dok je prodaja globalna, budući da je Acana veoma cenjena prirodna hrana, dobijena od svežih sastojaka, pri čemu je cena konkurentna. Acana hrana osmišljena je kao što bliža zamena za prirodnu ishranu pasa (sa vukom kao modelom), pa tako uključuje sve delove divljači i ima veći procenat mesa u odnosu na druge hrane",
        cena: 3500,
        zivotinja: "Pas",
        kolicina: 1,
        popust: 3000,
      },
      {
        id: 3,
        vrsta: "Hrana",
        Slika1: AcanaCat1_8kg,
        naslov: "Acana Cat Classic 2kg",
        opis: "Acana hrana za mačke sadrži sva tkiva životinja koje bi mačka jela u prirodi, a linije hrane podeljene su prema tipu lovišta i obuhvataju čak 70% proteina. Cena Acana hrane za mačke je nešto viša u odnosu na druge brendove, što je više nego opravdano sastavom i kontrolom kvaliteta Acana hrane.",
        cena: 3800,
        zivotinja: "Mačka",
        kolicina: 1,
        popust: 3200,
      },
      {
        id: 4,
        vrsta: "Hrana",
        Slika1: AkinuKonzervaGovedina,
        naslov: "Akinu Konzerva Govedina",
        opis: "Češka firma AKINU sa hranom I opremom za kućne ljubimce sa više od 27 godina iskustva I tradicije na evropskom tržištu.Nude celokupnu ponudu asortimana hrane I opreme za kućne ljubimce koja proizlazi iz stabilne saradnje sa proizvodjaćima iz celog sveta.",
        cena: 190,
        zivotinja: "Mačka",
        kolicina: 1,
        popust: undefined,
      },
      {
        id: 5,
        vrsta: "Hrana",
        Slika1: AkinuKonzervaPiletina,
        naslov: "Akinu Konzerva Piletina",
        opis: "Češka firma AKINU sa hranom I opremom za kućne ljubimce sa više od 27 godina iskustva I tradicije na evropskom tržištu.Nude celokupnu ponudu asortimana hrane I opreme za kućne ljubimce koja proizlazi iz stabilne saradnje sa proizvodjaćima iz celog sveta.",
        cena: 190,
        zivotinja: "Mačka",
        kolicina: 1,
        popust: undefined,
      },
      {
        id: 6,
        vrsta: "Hrana",
        Slika1: ZoluxPapagaj,
        naslov: "Zolux Nutrimeal Hrana za Papagaje",
        opis: "Francuska kompanije Zolux je jedan od najvećih evropskih proizvođača hrane i opreme za životinje. Dok se drugi poznati brendovi fokusiraju uglavnom na hranu, kompanija Zolux teži da ponudi apsolutno sve što je potrebno za zdrav i prijatan zajednički život ljubimaca i ljudi. Istorija kompanije je duga preko 80 godina, a iako prodaje svoje proizvode u 55 zemalja, tri četvrtine proizvodnje je i dalje u Evropi, uglavnom u Francuskoj.",
        cena: 650,
        zivotinja: "Papagaj",
        kolicina: 1,
        popust: undefined,
      },
      {
        id: 7,
        vrsta: "Orglice i povoci",
        Slika1: ZoluxAmZaMacku,
        naslov: "Zolux Am ZaMacku",
        opis: "Francuska kompanije Zolux je jedan od najvećih evropskih proizvođača hrane i opreme za životinje. Dok se drugi poznati brendovi fokusiraju uglavnom na hranu, kompanija Zolux teži da ponudi apsolutno sve što je potrebno za zdrav i prijatan zajednički život ljubimaca i ljudi. Istorija kompanije je duga preko 80 godina, a iako prodaje svoje proizvode u 55 zemalja, tri četvrtine proizvodnje je i dalje u Evropi, uglavnom u Francuskoj.",
        cena: 600,
        zivotinja: "Mačka",
        kolicina: 1,
        popust: undefined,
      },
      {
        id: 8,
        vrsta: "Ogrlice i povoci",
        Slika1: ZoluxOgrlica,
        naslov: "Zolux Ogrlica",
        opis: "Francuska kompanije Zolux je jedan od najvećih evropskih proizvođača hrane i opreme za životinje. Dok se drugi poznati brendovi fokusiraju uglavnom na hranu, kompanija Zolux teži da ponudi apsolutno sve što je potrebno za zdrav i prijatan zajednički život ljubimaca i ljudi. Istorija kompanije je duga preko 80 godina, a iako prodaje svoje proizvode u 55 zemalja, tri četvrtine proizvodnje je i dalje u Evropi, uglavnom u Francuskoj.",
        cena: 1100,
        zivotinja: "Pas",
        kolicina: 1,
        popust: undefined,
      },
      {
        id: 9,
        vrsta: "Ogrlice i povoci",
        Slika1: ZoluxOgrlicaSaDrzacem,
        naslov: "Zolux Ogrlica sa Drzacem",
        opis: "Francuska kompanije Zolux je jedan od najvećih evropskih proizvođača hrane i opreme za životinje. Dok se drugi poznati brendovi fokusiraju uglavnom na hranu, kompanija Zolux teži da ponudi apsolutno sve što je potrebno za zdrav i prijatan zajednički život ljubimaca i ljudi. Istorija kompanije je duga preko 80 godina, a iako prodaje svoje proizvode u 55 zemalja, tri četvrtine proizvodnje je i dalje u Evropi, uglavnom u Francuskoj.",
        cena: 4700,
        zivotinja: "Pas",
        kolicina: 1,
        popust: undefined,
      },
      {
        id: 10,
        vrsta: "Ogrlice i povoci",
        Slika1: ZoluxPovodacZaMacke,
        naslov: "Zolux Povodac za Macke",
        opis: "Francuska kompanije Zolux je jedan od najvećih evropskih proizvođača hrane i opreme za životinje. Dok se drugi poznati brendovi fokusiraju uglavnom na hranu, kompanija Zolux teži da ponudi apsolutno sve što je potrebno za zdrav i prijatan zajednički život ljubimaca i ljudi. Istorija kompanije je duga preko 80 godina, a iako prodaje svoje proizvode u 55 zemalja, tri četvrtine proizvodnje je i dalje u Evropi, uglavnom u Francuskoj.",
        cena: 480,
        zivotinja: "Mačka",
        kolicina: 1,
        popust: undefined,
      },
      {
        id: 11,
        vrsta: "Kavez i oprema",
        Slika1: ZoluxKavezSaPostoljem,
        naslov: "Zolux Kavez sa Postoljem",
        opis: "Francuska kompanije Zolux je jedan od najvećih evropskih proizvođača hrane i opreme za životinje. Dok se drugi poznati brendovi fokusiraju uglavnom na hranu, kompanija Zolux teži da ponudi apsolutno sve što je potrebno za zdrav i prijatan zajednički život ljubimaca i ljudi. Istorija kompanije je duga preko 80 godina, a iako prodaje svoje proizvode u 55 zemalja, tri četvrtine proizvodnje je i dalje u Evropi, uglavnom u Francuskoj.",
        cena: 11600,
        zivotinja: "Papagaj",
        kolicina: 1,
        popust: 9800,
      },
      {
        id: 12,
        vrsta: "Kavez i oprema",
        Slika1: ZoluxKavez,
        naslov: "Zolux Kavez",
        opis: "Francuska kompanije Zolux je jedan od najvećih evropskih proizvođača hrane i opreme za životinje. Dok se drugi poznati brendovi fokusiraju uglavnom na hranu, kompanija Zolux teži da ponudi apsolutno sve što je potrebno za zdrav i prijatan zajednički život ljubimaca i ljudi. Istorija kompanije je duga preko 80 godina, a iako prodaje svoje proizvode u 55 zemalja, tri četvrtine proizvodnje je i dalje u Evropi, uglavnom u Francuskoj.",
        cena: 6300,
        zivotinja: "Papagaj",
        kolicina: 1,
        popust: undefined,
      },
      {
        id: 13,
        vrsta: "Kavez i oprema",
        Slika1: ZoluxPojilica,
        naslov: "Zolux Pojilica",
        opis: "Francuska kompanije Zolux je jedan od najvećih evropskih proizvođača hrane i opreme za životinje. Dok se drugi poznati brendovi fokusiraju uglavnom na hranu, kompanija Zolux teži da ponudi apsolutno sve što je potrebno za zdrav i prijatan zajednički život ljubimaca i ljudi. Istorija kompanije je duga preko 80 godina, a iako prodaje svoje proizvode u 55 zemalja, tri četvrtine proizvodnje je i dalje u Evropi, uglavnom u Francuskoj.",
        cena: 350,
        zivotinja: "Papagaj",
        kolicina: 1,
        popust: undefined,
      },
      {
        id: 14,
        vrsta: "Kavez i oprema",
        Slika1: ZoluxStalakZaKavez,
        naslov: "Zolux Stalak za Kavez",
        opis: "Francuska kompanije Zolux je jedan od najvećih evropskih proizvođača hrane i opreme za životinje. Dok se drugi poznati brendovi fokusiraju uglavnom na hranu, kompanija Zolux teži da ponudi apsolutno sve što je potrebno za zdrav i prijatan zajednički život ljubimaca i ljudi. Istorija kompanije je duga preko 80 godina, a iako prodaje svoje proizvode u 55 zemalja, tri četvrtine proizvodnje je i dalje u Evropi, uglavnom u Francuskoj.",
        cena: 7900,
        zivotinja: "Papagaj",
        kolicina: 1,
        popust: 6500,
      },
      {
        id: 15,
        vrsta: "Hrana",
        Slika1: ZoluxNutrimealHranaZaCincile800g,
        naslov: "Zolux Nutrimeal Hrana za Činčile 800g",
        opis: "Francuska kompanije Zolux je jedan od najvećih evropskih proizvođača hrane i opreme za životinje. Dok se drugi poznati brendovi fokusiraju uglavnom na hranu, kompanija Zolux teži da ponudi apsolutno sve što je potrebno za zdrav i prijatan zajednički život ljubimaca i ljudi. Istorija kompanije je duga preko 80 godina, a iako prodaje svoje proizvode u 55 zemalja, tri četvrtine proizvodnje je i dalje u Evropi, uglavnom u Francuskoj.",
        cena: 520,
        zivotinja: "Glodari",
        kolicina: 1,
        popust: undefined,
      },
      {
        id: 16,
        vrsta: "Kavez i oprema",
        Slika1: ZoluxEhopTriKavezZaHrčke,
        naslov: "Zolux EhopTri Kavez za Hrčke",
        opis: "Francuska kompanije Zolux je jedan od najvećih evropskih proizvođača hrane i opreme za životinje. Dok se drugi poznati brendovi fokusiraju uglavnom na hranu, kompanija Zolux teži da ponudi apsolutno sve što je potrebno za zdrav i prijatan zajednički život ljubimaca i ljudi. Istorija kompanije je duga preko 80 godina, a iako prodaje svoje proizvode u 55 zemalja, tri četvrtine proizvodnje je i dalje u Evropi, uglavnom u Francuskoj.",
        cena: 6400,
        zivotinja: "Glodari",
        kolicina: 1,
        popust: undefined,
      },
      {
        id: 17,
        vrsta: "Igračke",
        Slika1: flamingoDinaLopticaZaPse,
        naslov: "Flamingo Dina Loptica",
        opis: "Flamingo je poznati evropski brend opreme i dodataka visokog kvaliteta za sve domaće kućne ljubimce, koji pridaje veliki značaj kvalitetu i funkcionalnosti proizvoda.",
        cena: 420,
        zivotinja: "Pas",
        kolicina: 1,
        popust: undefined,
      },
      {
        id: 18,
        vrsta: "Igračke",
        Slika1: ZoluxKoska,
        naslov: "Zolux Koska",
        opis: "Francuska kompanije Zolux je jedan od najvećih evropskih proizvođača hrane i opreme za životinje. Dok se drugi poznati brendovi fokusiraju uglavnom na hranu, kompanija Zolux teži da ponudi apsolutno sve što je potrebno za zdrav i prijatan zajednički život ljubimaca i ljudi. Istorija kompanije je duga preko 80 godina, a iako prodaje svoje proizvode u 55 zemalja, tri četvrtine proizvodnje je i dalje u Evropi, uglavnom u Francuskoj.",
        cena: 550,
        zivotinja: "Pas",
        kolicina: 1,
        popust: undefined,
      },
      {
        id: 19,
        vrsta: "Igračke",
        Slika1: FlamingoIgračkaMišnaNavijanjeAsher,
        naslov: "Flamingo Igračka Miš na Navijanje",
        opis: "Flamingo je poznati evropski brend opreme i dodataka visokog kvaliteta za sve domaće kućne ljubimce, koji pridaje veliki značaj kvalitetu i funkcionalnosti proizvoda.",
        cena: 450,
        zivotinja: "Mačka",
        kolicina: 1,
        popust: undefined,
      },
      {
        id: 20,
        vrsta: "Igračke",
        Slika1: FlamingoIgračkaŠtapsaPerjem,
        naslov: "Flamingo Igračka Štap sa Perjem",
        opis: "Flamingo je poznati evropski brend opreme i dodataka visokog kvaliteta za sve domaće kućne ljubimce, koji pridaje veliki značaj kvalitetu i funkcionalnosti proizvoda.",
        cena: 270,
        zivotinja: "Mačka",
        kolicina: 1,
        popust: undefined,
      },
      {
        id: 21,
        vrsta: "Igračke",
        Slika1: FlamingoIgračkaŠtapZaPecanje,
        naslov: "Flamingo Igračka Štap za Pecanje",
        opis: "Flamingo je poznati evropski brend opreme i dodataka visokog kvaliteta za sve domaće kućne ljubimce, koji pridaje veliki značaj kvalitetu i funkcionalnosti proizvoda.",
        cena: 970,
        zivotinja: "Mačka",
        kolicina: 1,
        popust: undefined,
      },
      {
        id: 22,
        vrsta: "Hrana",
        Slika1: AcanaHeritageAdultSmallBreed6kg,
        naslov: "Acana Heritage Adult Small Breed 6kg",
        opis: "GoFox Outfitters Quick Grill je svestran i praktičan dodatak svakoj opremi za kuvanjee na otvorenom. Njegova kombinacija prenosivosti, izdržljivosti i jednostavnosti upotrebe čini ga izvanrednim izborom za one koji uživaju u roštiljanju u pokretu. Bilo da kampujete u divljini, slavite na sportskim događanjima ili uživate u pikniku u parku, ovaj roštilj omogućava jednostavnu pripremu ukusnih obroka. Sa svojom brzom montažom i učinkovitim raspodeljenja toplote, Quick Grill je dizajniran da poboljša vaše iskustvo kuvanja na otvorenom.",
        cena: 7900,
        zivotinja: "Pas",
        kolicina: 1,
        popust: undefined,
      },
      {
        id: 23,
        vrsta: "Hrana",
        Slika1: AcanaHeritagePuppyJunior2kg,
        naslov: "Acana Heritage Puppy & Junior 2kg",
        opis: "GoFox Outfitters Quick Grill je svestran i praktičan dodatak svakoj opremi za kuvanjee na otvorenom. Njegova kombinacija prenosivosti, izdržljivosti i jednostavnosti upotrebe čini ga izvanrednim izborom za one koji uživaju u roštiljanju u pokretu. Bilo da kampujete u divljini, slavite na sportskim događanjima ili uživate u pikniku u parku, ovaj roštilj omogućava jednostavnu pripremu ukusnih obroka. Sa svojom brzom montažom i učinkovitim raspodeljenja toplote, Quick Grill je dizajniran da poboljša vaše iskustvo kuvanja na otvorenom.",
        cena: 3600,
        zivotinja: "Pas",
        kolicina: 1,
        popust: undefined,
      },
      {
        id: 24,
        vrsta: "Hrana",
        Slika1: AkinuMinistickiesKomadići,
        naslov: "Akinu Ministickies Komadići Govedine",
        opis: "Češka firma AKINU sa hranom I opremom za kućne ljubimce sa više od 27 godina iskustva I tradicije na evropskom tržištu.Nude celokupnu ponudu asortimana hrane I opreme za kućne ljubimce koja proizlazi iz stabilne saradnje sa proizvodjaćima iz celog sveta.",
        cena: 280,
        zivotinja: "Mačka",
        kolicina: 1,
        popust: undefined,
      },
      {
        id: 25,
        vrsta: "Hrana",
        Slika1: AkinuCrunchiesTrioMixPoslasticezaMačke,
        naslov: "Akinu Crunchies Trio Mix Poslastice",
        opis: "Češka firma AKINU sa hranom I opremom za kućne ljubimce sa više od 27 godina iskustva I tradicije na evropskom tržištu.Nude celokupnu ponudu asortimana hrane I opreme za kućne ljubimce koja proizlazi iz stabilne saradnje sa proizvodjaćima iz celog sveta.",
        cena: 130,
        zivotinja: "Mačka",
        kolicina: 1,
        popust: undefined,
      },
      {
        id: 26,
        vrsta: "Hrana",
        Slika1: VerseleLagaCompleteChinchillaDegu500g,
        naslov: "Versele-Laga Chinchilla & Degu 500g",
        opis: "Versele-Laga je belgijski brend čija je ponuda izuzetno bogata i kvalitetna. Kompanija proizvodi hranu za sve vrste ljubimaca, pri čemu je izbor vrlo raznovrstan, bilo da je reč o psima i mačkama ili glodarima, ribama i drugim ljubimcima. Iako su svi vlasnici ptica ili glodara odavno čuli za ovaj brend, među vlasnicima pasa i mačaka nije toliko poznat, iako je hrana odličnog kvaliteta.",
        cena: 620,
        zivotinja: "Glodari",
        kolicina: 1,
        popust: 530,
      },
      {
        id: 27,
        vrsta: "Hrana",
        Slika1: VitakraftPelletsHranaZaČinčile1kg,
        naslov: "Vitakraft Pellets Hrana za Činčile 1kg",
        opis: "Vitakraft od malog poljoprivrednog trgovca do međunarodne grupe proizvođača hrane za kućne ljubimce. Ono što je počelo kao mala prodavnica hrane za kućne ljubimce u selu Heiligenrode blizu Bremena u Nemačkoj, pre više od 180 godina, razvilo se u jedno od najuspešnijih kompanija u industriji hrane i opreme za kućne ljubimce, koja uspešno posluje širom Evrope, Severne i Južne Amerike i Azije.",
        cena: 330,
        zivotinja: "Glodari",
        kolicina: 1,
        popust: undefined,
      },
      {
        id: 28,
        vrsta: "Igračka",
        Slika1: KongIgračkaAirDogTegsaLopticama,
        naslov: "Kong Igračka Teg sa Lopticama",
        opis: "Čvrstoća i sposobnost poskakaivanja bili su insprijacija za nastanak KONG igračaka.KONG asortiman danas obuhvaća igračke za pse i mačke, raznih oblika i materijala, poslastice te opremu za ljubimce.",
        cena: 1700,
        zivotinja: "Pas",
        kolicina: 1,
        popust: undefined,
      },
      {
        id: 29,
        vrsta: "Hrana",
        Slika1: WhiskasBriketiTunjevina300g,
        naslov: "Whiskas Briketi Tunjevina 300g",
        opis: "Whiskas hrana za mačke proizvodi se skoro 90 godina i to je najstarija hrana za životinje koja danas postoji. Whiskas pripada kompaniji Mars, kao i mnogi drugi brendovi hrane za životinje, što garantuje dobru kontrolu kvaliteta.",
        cena: 200,
        zivotinja: "Mačke",
        kolicina: 1,
        popust: undefined,
      },
];